### ISSUE TITLE
Wersjonowanie danych klientów

### ISSUE THREAD

**Issue by kszysix** [kszysix/dental-data-procesing#10]

**Comment by kszysix** [comment]
W jaki sposób chcemy zrealizować wersjonowanie na froncie? Jakaś lista dostępnych wersji? czy buttony ze strzałkami i w lewo jak się kliknie to jest starsza wersja?
@fijka

**Comment by fijka** [comment]
Ja bym chyba wrzuciła tam posortowany po czasie select z wyborem. Dorzucenie strzałek też nie powinno być problemem.
![image](https://user-images.githubusercontent.com/57313936/104084623-14ccfa00-5249-11eb-8e72-ffe7197e1e86.png)
