### ISSUE TITLE
Zanikanie niezapisanych danych przy przejściu do starszej wersji

### ISSUE THREAD

**Issue by kszysix** [kszysix/dental-data-procesing#11]
Może zamiast robić skomplikowane zapamiętywanie niezapisanych danych, dać tutaj popup który informuje że niezapisane dane zostaną usunięte , kliknij ok jezeli chcesz zobaczyć starsze wersje

**Comment by fijka** [comment]
O, bardzo w porządku rozwiązanie. Też się zastanawiałam nad tym problemem i o tym nie pomyślałam. Ale wtedy wyświetlać popup zawsze przy jakimkolwiek przejściu? Czy tylko przy przejściu od najnowszej wersji do jednej wstecz?
