### ISSUE TITLE
Oznaczenia wykonane przez komendy głosowe, wykonują się wszystkie po zakończeniu komunikacji głosowej

### ISSUE THREAD

**Issue by kszysix** [kszysix/dental-data-procesing#5]
Powinny pojawiać się od razu po komendzie.

**Comment by kszysix** [comment]
Mogłabyś proszę spojrzeć? to jest mój kawałek kodu ale nie wiem jak to zrobić na froncie. 
Ogólna funkcja `mic()` w dentalDiagram, a potem `setToothPartDesease()` która powinna zmienić kolor zęba od razu a zmienia po zakończeniu funkcji `mic()`.

**Comment by kszysix** [comment]
@fijka

**Comment by fijka** [comment]
Jasne, zobaczę
