### ISSUE TITLE
Części zęba powinny być ustawione lustrzanie wobec jedynek

### ISSUE THREAD

**Issue by kszysix** [kszysix/dental-data-procesing#6]

**Comment by kszysix** [comment]
Chodzi o to co mi tłumaczyłaś ostatnio że w zależności od ćwiartki ząb ma inaczej ustawione powierzchnie. Czy ja mam coś tutaj zrobić? @fijka

**Comment by fijka** [comment]
Nie, ja to zrobię u siebie @kszysix
